version: "3.2"
services:
  db:
    image: postgres:15
    ports:
      - "54320:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_volumes:/var/lib/postgresql/data
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh command.sh
    tty: true
    stdin_open: true
    volumes:
      - .:/app
      - gem-local:/usr/local/bundle
      - node-local:/app/node_modules
      - ./tmp/letter_opener:/app/tmp/letter_opener
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      RAILS_ENV: ${RAILS_ENV}
volumes:
  db_volumes:
  gem-local:
  node-local:
